[View in Colaboratory](https://colab.research.google.com/github/s16397/ADD/blob/master/tmp.ipynb)

In [3]:
import os
import pandas as pd
import numpy as np

from keras.utils import np_utils

array = np.zeros([3,4])
array[0]


array([0., 0., 0., 0.])

In [4]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
# define example
data = [3, 3, 2, 0, 3, 2, 2, 1, 0, 1]
data = array(data)
print(data)
# one hot encode
encoded = to_categorical(data)
print(encoded)
# invert encoding
inverted = argmax(encoded[1])
print(inverted)

[3 3 2 0 3 2 2 1 0 1]
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
3


In [173]:
df = pd.DataFrame({'input1': np.array([ 1.0, 2.0, 3.0, 4.0,100.0]) ,'input2': np.array([ 5.0, 6.0, 7.0, 8.0,100.0]), 'label': [0,1,2,1,0]})


def get_x_and_y_arrays_as_dict(df, w=3, k=1):
  
  max_offset = df.shape[0] - w - k + 1

  y_matrix = np_utils.to_categorical(df.label)
  print('Y MATRIX: ', y_matrix)
  unique_labels_num = len(np.unique(df.label))
  print('UNIQUE:', unique_labels_num)

  x_array = np.zeros([max_offset , w * 2])
  y_array = np.zeros([max_offset , unique_labels_num])
  print('zeros x shape: ',x_array.shape)
  print('zeros y shape: ',y_array.shape)

  for i in range(0, max_offset):
    tmp = df.iloc[i:i+w,0:2].values.flatten()
    x_array[i]=tmp
    y_index = i + w  + k -1
    y_array[i] = y_matrix[y_index]
  
  return {'x': x_array, 'y': y_array}


x_y = get_x_and_y_arrays_as_dict(df, w=2, k=1)
print("dict x shape")
print(x_y['x'].shape)
print("dict y shape")
print(x_y['y'].shape)


  

# print(type(y_matrix[0]))
# print(y_matrix[1])

# i=0
# for arr in tmp:
#   print(i)
#   i = i+1
#   for el in arr:
#     print(el.shape)
df.iloc[:,2]

Y MATRIX:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
UNIQUE: 3
zeros x shape:  (3, 4)
zeros y shape:  (3, 3)
dict x shape
(3, 4)
dict y shape
(3, 3)


0    0
1    1
2    2
3    1
4    0
Name: label, dtype: int64

In [0]:
def get_csv_file_as_df(csv_filename):
  
  !if [ ! -d ADD ]; then git clone "https://github.com/s16397/ADD.git" ADD; fi
  
  add_dir = './ADD'
  csv_filepath = os.path.join(add_dir, csv_filename)
  
  # read file as df
  df = pd.read_csv(csv_filepath, header='infer')

  return df


def oblicz_roznice_kursu_norm(kurs_otwarcia, kurs_zamkniecia):
  diff = (kurs_zamkniecia / kurs_otwarcia) - 1
  if (diff > 0.01):
    return 2
  elif (diff < -0.01):
    return 1
  else:
    return 0

def preprocess_data(df, verbose=0):
  
  # roznica kursu: 2-wzrost, 1-spadek, 0-bez zmian
  df['roznica_kursu'] = df['Zamkniecie'] - df['Otwarcie']
  df['roznica_kursu_norm'] = df.apply(lambda row: oblicz_roznice_kursu_norm(row['Otwarcie'], row['Zamkniecie']),axis=1) 
  
  # find max value of: Otwarcie, Najwyzszy, Najnizszy, Zamkniecie
  max_stock_index = df.iloc[:,1:5].max().max()
  
  # find min value of: Otwarcie, Najwyzszy, Najnizszy, Zamkniecie
  min_stock_index = df.iloc[:,1:5].min().min()
  
  # find mean values for: Otwarcie, Najwyzszy, Najnizszy, Zamkniecie
  mean_values_serie = df.iloc[:,1:5].mean()
  
  # find max of: Wolumen
  max_volume = df.Wolumen.max()
  
  # find min of: Wolumen
  min_volume = df.Wolumen.min()
  
  # find avg of: Wolumen
  avg_volume = df.Wolumen.mean()
  
  if(verbose):
    print('**************** STATISTICS ****************')
    print('MAX(Otwarcie, Najwyzszy, Najnizszy, Zamkniecie)= ', max_stock_index)
    print('MIN(Otwarcie, Najwyzszy, Najnizszy, Zamkniecie)= ', min_stock_index)
    print('AVG(Otwarcie)=', mean_values_serie.loc['Otwarcie'])
    print('AVG(Najwyzszy)=', mean_values_serie.loc['Najwyzszy'])
    print('AVG(Najnizszy)=', mean_values_serie.loc['Najnizszy'])
    print('AVG(Zamkniecie)=', mean_values_serie.loc['Zamkniecie'])
    print('AVG(Otwarcie, Najwyzszy, Najnizszy, Zamkniecie)= ', mean_values_serie.mean())
    print('MAX(Wolumen)', max_volume)
    print('MIN(Wolumen)', min_volume)
    print('AVG(Wolumen)', avg_volume)
    print('**************** **************** ****************')
  
  # Normalize Otwarcie
  df.insert(6, 'Otwarcie_norm', df.Otwarcie.apply(
      lambda otwarcie: normalize_value_to_zero_one(otwarcie,
                                                   min_stock_index,
                                                   max_stock_index)))
  # Normalize Najwyzszy
  df.insert(7, 'Najwyzszy_norm', df.Najwyzszy.apply(
      lambda najwyzszy: normalize_value_to_zero_one(najwyzszy,
                                                   min_stock_index,
                                                   max_stock_index)))
  
  # Normalize Najnizszy
  df.insert(8, 'Najnizszy_norm', df.Najnizszy.apply(
      lambda najnizszy: normalize_value_to_zero_one(najnizszy,
                                                   min_stock_index,
                                                   max_stock_index)))
  
  # Normalize Zamkniecie
  df.insert(9, 'Zamkniecie_norm',df.Zamkniecie.apply(
      lambda zamkniecie: normalize_value_to_zero_one(zamkniecie,
                                                   min_stock_index,
                                                   max_stock_index)))
  # Normalize Wolumen
  df.insert(10, 'Wolumen_norm', df.Wolumen.apply(
      lambda wolumen: normalize_value_to_zero_one(wolumen,
                                                 min_volume,
                                                 max_volume)))
  
  return df

def normalize_value_to_zero_one(value, min_value, max_value):
  return (value - min_value) / (max_value - min_value)


In [33]:
df = get_csv_file_as_df(csv_filename='wig20_d-trening.csv')

pro = preprocess_data(df)

pro.head(10)

# processed_df = preprocess_data(df=df, verbose=0)

# processed_df.iloc[0:10,:]

one_index = pro.loc[pro['roznica_kursu_norm'] == 0]

one_index
# for idx in one_index:
#   print(idx)



Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie   Wolumen  \
1     2012-01-03   2203.07    2207.93    2184.10     2204.27  35639348   
2     2012-01-04   2197.87    2200.78    2160.82     2183.98  53626894   
5     2012-01-10   2140.68    2164.57    2134.01     2138.06  26790974   
6     2012-01-11   2151.91    2155.59    2119.32     2131.00  25183819   
8     2012-01-13   2182.11    2192.63    2147.67     2166.38  16137326   
10    2012-01-17   2209.14    2236.08    2207.21     2207.87  38577577   
11    2012-01-18   2225.97    2235.94    2204.98     2228.09  29851535   
12    2012-01-19   2239.67    2244.38    2200.99     2244.38  35769956   
13    2012-01-20   2243.23    2261.02    2232.64     2261.02  41967272   
14    2012-01-23   2260.36    2274.91    2252.88     2265.75  25812477   
15    2012-01-24   2266.41    2272.49    2251.21     2264.78  23685512   
18    2012-01-27   2307.13    2330.56    2302.00     2306.37  32741246   
19    2012-01-30   2299.47    2316.62    2286.35     2316.62  15435754   
20    2012-01-31   2323.93    2356.21    2322.04     2332.17  34472945   
22    2012-02-02   2378.68    2380.42    2357.39     2371.09  22622172   
23    2012-02-03   2368.73    2397.61    2362.07     2374.47  19969189   
24    2012-02-06   2370.99    2390.27    2362.60     2390.27  19570088   
25    2012-02-07   2390.97    2401.50    2358.43     2374.64  35003651   
26    2012-02-08   2383.73    2391.17    2368.10     2376.65  28130735   
29    2012-02-13   2345.79    2350.46    2331.09     2342.29  11056385   
30    2012-02-14   2342.57    2360.73    2327.84     2329.32  25767674   
31    2012-02-15   2351.00    2353.78    2326.16     2335.41  26576722   
32    2012-02-16   2320.82    2346.47    2316.11     2319.33  24568121   
33    2012-02-17   2348.96    2359.89    2342.81     2359.89  18284322   
34    2012-02-20   2369.07    2379.84    2348.92     2348.92  18455826   
35    2012-02-21   2365.77    2366.33    2339.39     2352.13  14951997   
37    2012-02-23   2313.12    2335.49    2297.46     2297.46  35150118   
38    2012-02-24   2316.10    2327.63    2308.94     2311.89  28133552   
39    2012-02-27   2314.36    2314.36    2288.23     2313.28  20459428   
40    2012-02-28   2322.87    2328.62    2308.22     2319.30  16789907   
...          ...       ...        ...        ...         ...       ...   
1202  2016-10-26   1785.14    1790.94    1771.44     1779.73  25294669   
1203  2016-10-27   1780.78    1798.42    1779.74     1795.33  32624860   
1205  2016-10-31   1816.88    1831.49    1809.89     1814.66  27833606   
1207  2016-11-03   1764.66    1773.49    1756.86     1767.37  32701997   
1208  2016-11-04   1765.48    1766.13    1757.07     1758.22  17564259   
1209  2016-11-07   1773.16    1788.47    1755.40     1761.79  25201503   
1210  2016-11-08   1767.24    1783.22    1767.24     1783.22  20600260   
1212  2016-11-10   1800.19    1831.76    1796.75     1796.75  44102443   
1214  2016-11-15   1757.25    1767.71    1746.95     1754.02  36263626   
1215  2016-11-16   1757.61    1769.29    1750.08     1758.54  33527644   
1217  2016-11-18   1736.82    1741.60    1717.55     1725.74  24377592   
1219  2016-11-22   1765.41    1779.86    1765.41     1775.66  27841299   
1221  2016-11-24   1798.00    1811.99    1795.48     1807.27  19371914   
1222  2016-11-25   1810.46    1812.80    1785.16     1796.30  30842716   
1224  2016-11-29   1777.84    1785.08    1771.13     1780.04  29194098   
1225  2016-11-30   1783.45    1808.78    1783.06     1798.22  80903768   
1227  2016-12-02   1787.79    1790.90    1777.56     1783.57  26538153   
1230  2016-12-07   1877.73    1900.64    1874.68     1889.51  53037801   
1232  2016-12-09   1916.66    1918.27    1888.59     1899.76  44104028   
1235  2016-12-14   1917.77    1935.51    1904.54     1934.87  41191584   
1237  2016-12-16   1913.05    1927.90    1903.57     1918.54  59526031   
1238  2016-12-19   1915.46    1929.48    1893.02     1924.67  28448920   
1239  2016-12-20

In [7]:
df = get_csv_file_as_df(csv_filename='wig20_d-trening.csv')
df.head(10)

Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie   Wolumen
0  2012-01-02   2150.60    2199.00    2143.87     2194.11   9743950
1  2012-01-03   2203.07    2207.93    2184.10     2204.27  35639348
2  2012-01-04   2197.87    2200.78    2160.82     2183.98  53626894
3  2012-01-05   2181.38    2181.38    2133.77     2157.43  19517064
4  2012-01-09   2164.20    2164.20    2126.71     2126.71  22781829
5  2012-01-10   2140.68    2164.57    2134.01     2138.06  26790974
6  2012-01-11   2151.91    2155.59    2119.32     2131.00  25183819
7  2012-01-12   2133.78    2183.29    2130.67     2166.99  25221052
8  2012-01-13   2182.11    2192.63    2147.67     2166.38  16137326
9  2012-01-16   2153.32    2185.09    2150.77     2182.94  17438271